### ISSUE TITLE
login in demo

### ISSUE THREAD

**Issue by devtechk** [qoomon/smart-life-webapp#1]
Hello, maybe this is not an issue but what is the email and pwd for the demo?
Thanks!

**Comment by qoomon** [comment]
it's not a demo, it's a SPA to access your devices. User email and password of your smart life account.

**Comment by devtechk** [comment]
Thank you, yes now I've tried using my smart life account but always return invalid pwd or email

**Comment by qoomon** [comment]
Ah yes I remember I had the same problem.

I created my smart life account by using my Google account. For some reason it only works if you register your account with an email and password in the first place.

Following steps fixed the issue for me.
* delete my smart life account
* recreate a smart live account by using my gmail address and password

**Comment by devtechk** [comment]
Yep I was writing back to you. Now it works!
I've created another account without gmail, i mean a linked the gmail one to the new one.
Now I'd like to put your proj inside my raspberry (probabily using docker).
I'll update you!

Do you plan to add extra feature like edit name of devices or something like this?

**Comment by qoomon** [comment]
Glad to hear it works. 

> Do you plan to add extra feature like edit name of devices or something like this?
No, my intention of this project was just to be able to toggle my coffee machine from my laptop :-D
Furthermore the is no easy to use API to manage devices in any way like renaming.

**Comment by devtechk** [comment]
Hehe cool, 
My purpouse was like the same of yours but not for the coffee machine just for my workstation eg. monitor, notebook , macbook, speaker in the same plug :)
