### ISSUE TITLE
API methods

### ISSUE THREAD

**Issue by jhonwimo** [qoomon/smart-life-webapp#94]
Thank you very much for the contribution, do you know where I can see the documentation of the api or what other methods it has? where did you see how to consume them, thank you

**Comment by qoomon** [comment]
Unfortunately I don't think the is a documentation :-(. I just got those endpoints from 
https://github.com/PaulAnnekov/tuyaha/blob/master/tuyaha/tuyaapi.py

Here are some more information about the api, however no api documentation.
https://github.com/PaulAnnekov/tuyaha/issues/22

**Comment by qoomon** [comment]
FYI There seem to be a new documented api https://github.com/tuya/tuya-smart-life

**Comment by jhonwimo** [comment]
Suddenly you know why this can happen, I call the api https://px1.tuyacn.com/homeassistant/skill?region=cn it shows me   {
    "payload": {
        "devices": [],
        "scenes": []
    },
    "header": {
        "code": "SUCCESS",
        "payloadVersion": 1
    }
}          the yuya shows the device but the method says that everything went well but it doesn't bring anything

**Comment by qoomon** [comment]
Sadly not all kinds of devices are supported
